on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Tests app
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install --upgrade -r requirements.txt
      - run: docker compose build
      - run: docker compose up -d
      - run: sleep 5
      - run: echo "BASE_URL=${BASE_URL}"
      - run: pytest test --junit-xml=test-results.xml
        env:
          BASE_URL: ${{ secrets.BASE_URL }}

      - run: docker compose logs app
        if: always()

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: Test results